# Generated by Django 5.0.7 on 2026-07-11 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(db_index=True, default='korona', max_length=80)),
                ('method', models.CharField(max_length=12)),
                ('url_path', models.TextField()),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('korona_id', models.UUIDField(unique=True)),
                ('number', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('revision', models.BigIntegerField(db_index=True, default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('korona_id', models.UUIDField(unique=True)),
                ('number', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('is_warehouse', models.BooleanField(default=False)),
                ('revision', models.BigIntegerField(db_index=True, default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('source', models.CharField(db_index=True, max_length=120)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('korona_store_order_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lists', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lists', to='orders.store')),
            ],
            options={
                'ordering': ['-order_date', 'store__number'],
                'unique_together': {('store', 'order_date')},
            },
        ),
        migrations.CreateModel(
            name='OrderListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stock_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('on_shelf_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('monthly_needed_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('suggested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('final_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_order_items', to=settings.AUTH_USER_MODEL)),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderlist')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_order_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product')),
            ],
            options={
                'ordering': ['row_order', 'id'],
                'unique_together': {('order_list', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ServiceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=80, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('disabled', 'Disabled'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('normalized_code', models.CharField(db_index=True, max_length=128)),
                ('container_size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='orders.product')),
            ],
            options={
                'unique_together': {('product', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalesDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_date', models.DateField(db_index=True)),
                ('quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('receipts_count', models.PositiveIntegerField(default=0)),
                ('last_receipt_revision', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product', 'sales_date'], name='orders_sale_store_i_6befd3_idx')],
                'unique_together': {('store', 'product', 'sales_date')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.UUIDField(db_index=True)),
                ('receipt_revision', models.BigIntegerField(db_index=True, default=0)),
                ('sales_date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product', 'sales_date'], name='orders_rece_store_i_e20ac7_idx')],
                'unique_together': {('receipt_id', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ordered', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lent', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('revision', models.BigIntegerField(db_index=True, default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='orders.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='orders.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product'], name='orders_prod_store_i_b764ec_idx')],
                'unique_together': {('product', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ProductMonthlyNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(db_index=True)),
                ('needed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('avg_daily_sales_30', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('avg_daily_sales_90', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('seasonal_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculation_version', models.CharField(default='weighted-v1', max_length=32)),
                ('last_calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.store')),
            ],
            options={
                'unique_together': {('store', 'product', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='orders.orderlistitem')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.store')),
            ],
            options={
                'unique_together': {('item', 'from_store')},
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(max_length=80)),
                ('last_revision', models.BigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store')),
            ],
            options={
                'unique_together': {('entity', 'store')},
            },
        ),
        migrations.CreateModel(
            name='UserGridPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid_key', models.CharField(max_length=128)),
                ('column_state', models.JSONField(blank=True, default=list)),
                ('filter_state', models.JSONField(blank=True, default=dict)),
                ('sort_state', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'grid_key')},
            },
        ),
    ]
