# Generated by Django 5.2.16 on 2026-07-16 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderlistitem_on_shelf_quantity_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('delivered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('general_notes', models.TextField(blank=True)),
                ('issue_notes', models.TextField(blank=True)),
                ('expected_cases', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered_cases', models.PositiveIntegerField(blank=True, null=True)),
                ('damaged_cases', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('needs_info', 'Needs more information'), ('issue_found', 'Issue found'), ('verified', 'Verified'), ('resolved', 'Resolved')], db_index=True, default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.store')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('boxes', 'Boxes'), ('damage', 'Damage'), ('notes', 'Notes')], db_index=True, max_length=16)),
                ('object_key', models.CharField(max_length=900, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='orders.delivery')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=16)),
                ('object_key', models.CharField(blank=True, max_length=900)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('asset_count', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('photo_added', 'Photo added'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('keywords_changed', 'Keywords changed'), ('downloaded', 'Downloaded')], db_index=True, max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('normalized_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_keywords_created', to=settings.AUTH_USER_MODEL)),
                ('deliveries', models.ManyToManyField(blank=True, related_name='keywords', to='orders.delivery')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'delivered_at'], name='orders_deli_status_b86a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['store', 'delivered_at'], name='orders_deli_store_i_ca1990_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['submitted_by', 'delivered_at'], name='orders_deli_submitt_db5b67_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryasset',
            index=models.Index(fields=['delivery', 'category', 'position'], name='orders_deli_deliver_a32d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['delivery', 'created_at'], name='orders_deli_deliver_f1d478_idx'),
        ),
    ]
