# Generated by Django 5.2.16 on 2026-07-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_delivery_deliveryasset_deliverybackup_deliveryevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssetReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('copying', 'Copying'), ('verified', 'Verified'), ('failed', 'Failed'), ('missing', 'Missing')], db_index=True, default='pending', max_length=16)),
                ('object_key', models.CharField(max_length=900)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('replicated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replica', to='orders.deliveryasset')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='orders_deli_status_aac223_idx')],
            },
        ),
    ]
